[package]
name = "precise_math"
version = "0.1.0"
authors = ["Éttore Leandro Tognoli <ettore.leandro.tognoli@gmail.com>"]

[lib]
name = "precise_math"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]
[dependencies.num]
version = "0.1.42"